//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SquaresDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vTopArtist
    {
        public string ArtistId { get; set; }
        public string Alias { get; set; }
        public Nullable<int> SetNumber { get; set; }
        public Nullable<int> AverageRating { get; set; }
        public Nullable<int> TotalViews { get; set; }
    }
}
