<?xml version="1.0" encoding="utf-8"?><Database Name="Squares" Class="DataClassesSquaresDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=squaresprototype.database.windows.net;Initial Catalog=Squares;User ID=SquaresAdmin;Encrypt=False;TrustServerCertificate=True" SettingsObjectName="SquaresDataLibrary.Properties.Settings" SettingsPropertyName="SquaresConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[__MigrationHistory]" Member="__MigrationHistories">
    <Type Name="__MigrationHistory">
      <Column Name="MigrationId" Type="System.String" DbType="NVarChar(150) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ContextKey" Type="System.String" DbType="NVarChar(300) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Model" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ProductVersion" Type="System.String" DbType="NVarChar(32) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Admin" Member="Admins">
    <Type Name="Admin">
      <Column Name="UserId" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleId" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="AspNetUserRole_Admin" Member="AspNetUserRole" ThisKey="UserId,RoleId" OtherKey="UserId,RoleId" Type="AspNetUserRole" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetRoles" Member="AspNetRoles">
    <Type Name="AspNetRole">
      <Column Name="Id" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Association Name="AspNetRole_AspNetUserRole" Member="AspNetUserRoles" ThisKey="Id" OtherKey="RoleId" Type="AspNetUserRole" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetUserClaims" Member="AspNetUserClaims">
    <Type Name="AspNetUserClaim">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="ClaimType" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ClaimValue" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="AspNetUser_AspNetUserClaim" Member="AspNetUser" ThisKey="UserId" OtherKey="Id" Type="AspNetUser" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetUserLogins" Member="AspNetUserLogins">
    <Type Name="AspNetUserLogin">
      <Column Name="LoginProvider" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProviderKey" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="AspNetUser_AspNetUserLogin" Member="AspNetUser" ThisKey="UserId" OtherKey="Id" Type="AspNetUser" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetUserRoles" Member="AspNetUserRoles">
    <Type Name="AspNetUserRole">
      <Column Name="UserId" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleId" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="AspNetUserRole_Admin" Member="Admin" ThisKey="UserId,RoleId" OtherKey="UserId,RoleId" Type="Admin" Cardinality="One" />
      <Association Name="AspNetUserRole_Author" Member="Author" ThisKey="UserId,RoleId" OtherKey="UserId,RoleId" Type="Author" Cardinality="One" />
      <Association Name="AspNetRole_AspNetUserRole" Member="AspNetRole" ThisKey="RoleId" OtherKey="Id" Type="AspNetRole" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="AspNetUser_AspNetUserRole" Member="AspNetUser" ThisKey="UserId" OtherKey="Id" Type="AspNetUser" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetUsers" Member="AspNetUsers">
    <Type Name="AspNetUser">
      <Column Name="Id" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="EmailConfirmed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PasswordHash" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SecurityStamp" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PhoneNumberConfirmed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TwoFactorEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LockoutEndDateUtc" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LockoutEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AccessFailedCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="ZipcodeId" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Orginization" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="RegistrationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Birthday" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="AspNetUser_AspNetUserClaim" Member="AspNetUserClaims" ThisKey="Id" OtherKey="UserId" Type="AspNetUserClaim" />
      <Association Name="AspNetUser_AspNetUserLogin" Member="AspNetUserLogins" ThisKey="Id" OtherKey="UserId" Type="AspNetUserLogin" />
      <Association Name="AspNetUser_AspNetUserRole" Member="AspNetUserRoles" ThisKey="Id" OtherKey="UserId" Type="AspNetUserRole" />
      <Association Name="AspNetUser_Collection" Member="Collections" ThisKey="Id" OtherKey="UserId" Type="Collection" />
      <Association Name="Zipcode_AspNetUser" Member="Zipcode" ThisKey="ZipcodeId" OtherKey="ZipcodeId" Type="Zipcode" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Author" Member="Authors">
    <Type Name="Author">
      <Column Name="RoleId" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Alias" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Author_Set" Member="Sets" ThisKey="UserId,RoleId" OtherKey="UserId,RoleId" Type="Set" />
      <Association Name="AspNetUserRole_Author" Member="AspNetUserRole" ThisKey="UserId,RoleId" OtherKey="UserId,RoleId" Type="AspNetUserRole" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Collection" Member="Collections">
    <Type Name="Collection">
      <Column Name="CollectionId" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SetId" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UserId" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Association Name="Collection_CollectionPiece" Member="CollectionPieces" ThisKey="CollectionId" OtherKey="CollectionId" Type="CollectionPiece" />
      <Association Name="AspNetUser_Collection" Member="AspNetUser" ThisKey="UserId" OtherKey="Id" Type="AspNetUser" IsForeignKey="true" />
      <Association Name="Set_Collection" Member="Set" ThisKey="SetId" OtherKey="SetId" Type="Set" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CollectionPiece" Member="CollectionPieces">
    <Type Name="CollectionPiece">
      <Column Name="CollectionId" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="PieceId" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Association Name="Collection_CollectionPiece" Member="Collection" ThisKey="CollectionId" OtherKey="CollectionId" Type="Collection" IsForeignKey="true" />
      <Association Name="Piece_CollectionPiece" Member="Piece" ThisKey="PieceId" OtherKey="PieceId" Type="Piece" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Piece" Member="Pieces">
    <Type Name="Piece">
      <Column Name="PieceId" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SetId" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Url" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Piece_CollectionPiece" Member="CollectionPieces" ThisKey="PieceId" OtherKey="PieceId" Type="CollectionPiece" />
      <Association Name="Set_Piece" Member="Set" ThisKey="SetId" OtherKey="SetId" Type="Set" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[Set]" Member="Sets">
    <Type Name="Set">
      <Column Name="SetId" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Rating" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ViewCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserId" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="RoleId" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Association Name="Set_Collection" Member="Collections" ThisKey="SetId" OtherKey="SetId" Type="Collection" />
      <Association Name="Set_Piece" Member="Pieces" ThisKey="SetId" OtherKey="SetId" Type="Piece" />
      <Association Name="Set_SetTag" Member="SetTags" ThisKey="SetId" OtherKey="SetId" Type="SetTag" />
      <Association Name="Author_Set" Member="Author" ThisKey="UserId,RoleId" OtherKey="UserId,RoleId" Type="Author" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SetTag" Member="SetTags">
    <Type Name="SetTag">
      <Column Name="TagId" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="SetId" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Association Name="Set_SetTag" Member="Set" ThisKey="SetId" OtherKey="SetId" Type="Set" IsForeignKey="true" />
      <Association Name="Tag_SetTag" Member="Tag" ThisKey="TagId" OtherKey="TagId" Type="Tag" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tag" Member="Tags">
    <Type Name="Tag">
      <Column Name="TagId" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Tag_SetTag" Member="SetTags" ThisKey="TagId" OtherKey="TagId" Type="SetTag" />
    </Type>
  </Table>
  <Table Name="dbo.Zipcode" Member="Zipcodes">
    <Type Name="Zipcode">
      <Column Name="ZipcodeId" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Zipcode" Member="Zipcode1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Zipcode_AspNetUser" Member="AspNetUsers" ThisKey="ZipcodeId" OtherKey="ZipcodeId" Type="AspNetUser" />
    </Type>
  </Table>
  <Table Name="dbo.vTopRated" Member="vTopRateds">
    <Type Name="vTopRated">
      <Column Name="SetId" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Rating" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ViewCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Alias" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.DeleteSet" Method="DeleteSet">
    <Parameter Name="SetId" Parameter="setId" Type="System.String" DbType="NVarChar(128)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.NewSet" Method="NewSet">
    <Parameter Name="SetId" Parameter="setId" Type="System.String" DbType="NVarChar(128)" />
    <Parameter Name="Title" Parameter="title" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="UserId" Parameter="userId" Type="System.String" DbType="NVarChar(128)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateSet" Method="UpdateSet">
    <Parameter Name="SetId" Parameter="setId" Type="System.String" DbType="NVarChar(128)" />
    <Parameter Name="Title" Parameter="title" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
</Database>